const { Game, Genre, SupportedPlatform } = require('../../db.js');

const gamesArray = [
  {
    "name": "The Legend of Zelda: Breath of the Wild",
    "image": "https://res.cloudinary.com/bits8/image/upload/v1694010552/f6yhlgzc47sveuthyom7.jpg",
    "description": "An open-world action-adventure game set in the fantasy realm of Hyrule.",
    "releaseDate": "March 3, 2017",
    "supportedPlatforms": ["Nintendo Switch", "Wii U"],
    "genre": ["Action", "Adventure"],
    "price": 35.90,
    "review": "Metacritic Score - 97/100",
    "stock": 27,
  },
  {
    "name": "The Witcher 3: Wild Hunt",
    "image": "https://res.cloudinary.com/bits8/image/upload/v1694108886/tew4ergptn4c1bf7mdyb.jpg",
    "description": "A sprawling open-world RPG where you play as Geralt of Rivia, a monster hunter.",
    "releaseDate": "May 19, 2015",
    "supportedPlatforms": ["PC", "PlayStation 4", "Xbox One", "Nintendo Switch"],
    "genre": ["RPG"],
    "price": 29.90,
    "review": "Metacritic Score - 93/100",
    "stock": 44,
  },
  {
    "name": "Red Dead Redemption 2",
    "image": "https://res.cloudinary.com/bits8/image/upload/v1694108970/rstfwrq9xp5cv5hkqcf7.jpg",
    "description": "An epic tale of life in America's unforgiving heartland during the late 1800s.",
    "releaseDate": "October 26, 2018",
    "supportedPlatforms": ["PC", "PlayStation 4", "Xbox One"],
    "genre": ["Action", "Adventure"],
    "price": 29.90,
    "review": "Metacritic Score - 97/100",
    "stock": 29,
  },
  {
    "name": "The Elder Scrolls V: Skyrim",
    "image": "https://res.cloudinary.com/bits8/image/upload/v1694108988/qtjcu9chowcqgzladhd5.jpg",
    "description": "An open-world RPG set in the fantasy world of Tamriel, known for its vastness and modding community.",
    "releaseDate": "November 11, 2011",
    "supportedPlatforms": ["PC", "PlayStation 3", "PlayStation 4", "Xbox 360", "Xbox One", "Nintendo Switch"],
    "genre": ["RPG"],
    "price": 24.90,
    "review": "Metacritic Score - 94/100",
    "stock": 35,
  },
  {
    "name": "Super Mario Odyssey",
    "image": "https://res.cloudinary.com/bits8/image/upload/v1694109009/ibwdc3ibgz14aprsolip.jpg",
    "description": "Mario embarks on a globe-trotting adventure to save Princess Peach from Bowser.",
    "releaseDate": "October 27, 2017",
    "supportedPlatforms": ["Nintendo Switch"],
    "genre": ["Platformer"],
    "price": 29.90,
    "review": "Metacritic Score - 97/100",
    "stock": 22,
  },
  {
    "name": "God of War (2018)",
    "image": "https://res.cloudinary.com/bits8/image/upload/v1694453489/vnvuw2f6jwgvxrv51iuz.jpg",
    "description": "Kratos returns, this time in Norse mythology, on a quest with his son Atreus.",
    "releaseDate": "April 20, 2018",
    "supportedPlatforms": ["PlayStation 4", "PlayStation 5"],
    "genre": ["Action", "Adventure"],
    "price": 11.50,
    "review": "Metacritic Score - 94/100",
    "stock": 38,
  },
  {
    "name": "Dark Souls III",
    "image": "https://res.clouinary.com/bits8/image/upload/v1694109053/zlwvlzkcclxk4ez7eegi.jpg",
    "description": "A challenging action RPG that tests your skills and patience in a dark and beautifully designed world.",
    "releaseDate": "April 12, 2016",
    "supportedPlatforms": ["PC", "PlayStation 4", "Xbox One"],
    "genre": ["Action", "RPG"],
    "price": 24.90,
    "review": "Metacritic Score - 89/100",
    "stock": 30,
  },
  {
    "name": "Hollow Knight",
    "image": "https://res.cloudinary.com/bits8/image/upload/v1694109152/nttx8tevxr8jy7hmybhq.jpg",
    "description": "An atmospheric and challenging action-adventure game set in a mysterious underground world.",
    "releaseDate": "February 24, 2017",
    "supportedPlatforms": ["PC", "PlayStation 4", "Xbox One", "Nintendo Switch"],
    "genre": ["Metroidvania"],
    "price": 25.50,
    "review": "Metacritic Score - 90/100",
    "stock": 25,
  },
  {
    "name": "Persona 5",
    "image": "https://res.cloudinary.com/bits8/image/upload/v1694447962/fzpfvxjoc9t7fn2nodv8.png",
    "description": "A stylish JRPG where you play as a high school student with secret supernatural powers.",
    "releaseDate": "April 4, 2017",
    "supportedPlatforms": ["PlayStation 3", "PlayStation 4"],
    "genre": ["JRPG"],
    "price": 12.90,
    "review": "Metacritic Score - 93/100",
    "stock": 40,
  },
  {
    "name": "Overwatch",
    "image": "https://res.cloudinary.com/bits8/image/upload/v1694109184/ccy4shisgjdllocrggxv.jpg",
    "description": "A team-based multiplayer first-person shooter with a diverse cast of heroes.",
    "releaseDate": "May 24, 2016",
    "supportedPlatforms": ["PC", "PlayStation 4", "Xbox One", "Nintendo Switch"],
    "genre": ["First-Person Shooter"],
    "price": 14.90,
    "review": "Metacritic Score - 90/100",
    "stock": 33,
  },
  {
    "name": "Cyberpunk 2077",
    "image": "https://res.cloudinary.com/bits8/image/upload/v1694109667/m60tvbiabbk7htkszktf.jpg",
    "description": "An open-world RPG set in a dystopian future, developed by CD Projekt Red.",
    "releaseDate": "December 10, 2020",
    "supportedPlatforms": ["PC", "PlayStation 4", "Xbox One"],
    "genre": ["RPG"],
    "price": 19.90,
    "review": "Metacritic Score - 56/100",
    "stock": 20,
  },
  {
    "name": "Celeste",
    "image": "https://res.cloudinary.com/bits8/image/upload/v1694109683/yv0luk6srleaxp5fb3b0.png",
    "description": "A challenging platformer with a touching narrative about mental health.",
    "releaseDate": "January 25, 2018",
    "supportedPlatforms": ["PC", "PlayStation 4", "Xbox One", "Nintendo Switch"],
    "genre": ["Platformer"],
    "price": 12.90,
    "review": "Metacritic Score - 94/100",
    "stock": 28,
  },
  {
    "name": "Minecraft",
    "image": "https://res.cloudinary.com/bits8/image/upload/v1694109702/x4le1esrzgudjww1h7qu.jpg",
    "description": "A sandbox game that allows players to build and explore their own blocky worlds.",
    "releaseDate": "November 18, 2011",
    "supportedPlatforms": ["PC", "Various consoles", "Mobile devices"],
    "genre": ["Sandbox"],
    "price": 29.90,
    "review": "Metacritic Score - 93/100",
    "stock": 24,
  },
  {
    "name": "Sekiro: Shadows Die Twice",
    "image": "https://res.cloudinary.com/bits8/image/upload/v1694109715/ccd1lxhi15redfavtczn.jpg",
    "description": "An action-adventure game set in feudal Japan, known for its challenging combat.",
    "releaseDate": "March 22, 2019",
    "supportedPlatforms": ["PC", "PlayStation 4", "Xbox One"],
    "genre": ["Action", "Adventure"],
    "price": 15.50,
    "review": "Metacritic Score - 90/100",
    "stock": 32,
  },
  {
    "name": "Monster Hunter: World",
    "image": "https://res.cloudinary.com/bits8/image/upload/v1694109732/nfwdpje31hjv3z0nymm2.jpg",
    "description": "An action RPG where you hunt down massive creatures in a lush open world.",
    "releaseDate": "January 26, 2018",
    "supportedPlatforms": ["PC", "PlayStation 4", "Xbox One"],
    "genre": ["Action", "RPG"],
    "price": 18.90,
    "review": "Metacritic Score - 90/100",
    "stock": 36,
  },
  {
    "name": "Grand Theft Auto V",
    "image": "https://res.cloudinary.com/bits8/image/upload/v1694109732/nfwdpje31hjv3z0nymm2.jpg",
    "description": "An open-world action-adventure game that follows the lives of three criminals in Los Santos.",
    "releaseDate": "September 17, 2013",
    "supportedPlatforms": ["PC", "PlayStation 3", "PlayStation 4", "Xbox 360", "Xbox One"],
    "genre": ["Action", "Adventure"],
    "price": 29.90,
    "review": "Metacritic Score - 96/100",
    "stock": 42,
  },
  {
    "name": "Death Stranding",
    "image": "https://res.cloudinary.com/bits8/image/upload/v1694446263/ivdjkckqotttiddrk6ze.jpg",
    "description": "A unique open-world game by Hideo Kojima that blends exploration, survival, and a mysterious narrative.",
    "releaseDate": "November 8, 2019",
    "supportedPlatforms": ["PC", "PlayStation 4"],
    "genre": ["Action", "Adventure"],
    "price": 12.90,
    "review": "Metacritic Score - 82/100",
    "stock": 31,
  },
  {
    "name": "Bloodborne",
    "image": "https://res.cloudinary.com/bits8/image/upload/v1694448295/onzzbcvglejc6h4g7sqm.gif",
    "description": "An action RPG with a gothic-horror setting and fast-paced, challenging combat.",
    "releaseDate": "March 24, 2015",
    "supportedPlatforms": ["PlayStation 4"],
    "genre": ["Action", "RPG"],
    "price": 17.80,
    "review": "Metacritic Score - 92/100",
    "stock": 26,
  },
  {
    "name": "Undertale",
    "image": "https://res.cloudinary.com/bits8/image/upload/v1694109787/h8xtga6ouufcywryc9aa.jpg",
    "description": "A unique indie RPG that allows players to choose between violence and mercy in a world of monsters.",
    "releaseDate": "September 15, 2015",
    "supportedPlatforms": ["PC", "Various consoles"],
    "genre": ["RPG"],
    "price": 15.80,
    "review": "Metacritic Score - 92/100",
    "stock": 34,
  },
  {
    "name": "Mortal Kombat 11",
    "image": "https://res.cloudinary.com/bits8/image/upload/v1694109795/ri0xadkrg1pah18ntel0.jpg",
    "description": "A brutal and fast-paced fighting game featuring a roster of iconic characters.",
    "releaseDate": "April 23, 2019",
    "supportedPlatforms": ["PC", "PlayStation 4", "Xbox One", "Nintendo Switch"],
    "genre": ["Fighting"],
    "price": 29.90,
    "review": "Metacritic Score - 83/100",
    "stock": 29,
  },
  {
    "name": "Resident Evil Village",
    "image": "https://res.cloudinary.com/bits8/image/upload/v1694110023/jvde04qqdotshzvi5dyr.png",
    "description": "The latest installment in the Resident Evil series, featuring first-person survival horror gameplay.",
    "releaseDate": "May 7, 2021",
    "supportedPlatforms": ["PC", "PlayStation 4", "PlayStation 5", "Xbox One", "Xbox Series X/S"],
    "genre": ["Survival Horror"],
    "price": 22.50,
    "review": "Metacritic Score - 84/100",
    "stock": 25,
  },
  {
    "name": "Control",
    "image": "https://res.cloudinary.com/bits8/image/upload/v1694448411/ea9suceh7rmootggfw1p.jpg",
    "description": "A mind-bending action-adventure game with a focus on paranormal abilities.",
    "releaseDate": "August 27, 2019",
    "supportedPlatforms": ["PC", "PlayStation 4", "PlayStation 5", "Xbox One", "Xbox Series X/S"],
    "genre": ["Action", "Adventure"],
    "price": 18.90,
    "review": "Metacritic Score - 82/100",
    "stock": 30,
  },
  {
    "name": "The Last of Us Part II",
    "image": "https://res.cloudinary.com/bits8/image/upload/v1694448531/kdwclwmtgzl71syw42dg.webp",
    "description": "A gripping action-adventure game that explores themes of revenge and redemption in a post-apocalyptic world.",
    "releaseDate": "June 19, 2020",
    "supportedPlatforms": ["PlayStation 4", "PlayStation 5"],
    "genre": ["Action", "Adventure"],
    "price": 24.90,
    "review": "Metacritic Score - 93/100",
    "stock": 27,
  },
  {
    "name": "Ghost of Tsushima",
    "image": "https://res.cloudinary.com/bits8/image/upload/v1694448649/p71yeayjkmx9ggebkenn.jpg",
    "description": "An open-world action-adventure game set in feudal Japan, where you play as a samurai.",
    "releaseDate": "July 17, 2020",
    "supportedPlatforms": ["PlayStation 4", "PlayStation 5"],
    "genre": ["Action", "Adventure"],
    "price": 29.90,
    "review": "Metacritic Score - 83/100",
    "stock": 23,
  },
  {
    "name": "Final Fantasy VII Remake",
    "image": "https://res.cloudinary.com/bits8/image/upload/v1694448736/win2mytadnnraecxtah8.jpg",
    "description": "A modern reimagining of the classic RPG, with stunning visuals and revamped gameplay.",
    "releaseDate": "April 10, 2020",
    "supportedPlatforms": ["PlayStation 4", "PlayStation 5"],
    "genre": ["RPG"],
    "price": 29.90,
    "review": "Metacritic Score - 87/100",
    "stock": 22,
  },
  {
    "name": "Assassin's Creed Valhalla",
    "image": "https://res.cloudinary.com/bits8/image/upload/v1694448805/jvdb44tx9b0rlt7amzet.jpg",
    "description": "Embark on a Viking saga in this action RPG set in the Dark Ages.",
    "releaseDate": "November 10, 2020",
    "supportedPlatforms": ["PC", "PlayStation 4", "PlayStation 5", "Xbox One", "Xbox Series X/S"],
    "genre": ["Action", "RPG"],
    "price": 24.90,
    "review": "Metacritic Score - 83/100",
    "stock": 19,
  },
  {
    "name": "Demon's Souls (2020)",
    "image": "https://res.cloudinary.com/bits8/image/upload/v1694452745/tsnn3dbictj1fvkog2yr.jpg",
    "description": "A remake of the classic action RPG, known for its punishing difficulty and breathtaking visuals.",
    "releaseDate": "November 12, 2020",
    "supportedPlatforms": ["PlayStation 5"],
    "genre": ["Action", "RPG"],
    "price": 34.90,
    "review": "Metacritic Score - 92/100",
    "stock": 18,
  },
  {
    "name": "Hades",
    "image": "https://res.cloudinary.com/bits8/image/upload/v1694110290/vzyodg1z25400ztwp7vc.png",
    "description": "A roguelike dungeon crawler where you battle through the underworld of Greek mythology.",
    "releaseDate": "September 17, 2020",
    "supportedPlatforms": ["PC", "Nintendo Switch"],
    "genre": ["Roguelike"],
    "price": 19.90,
    "review": "Metacritic Score - 93/100",
    "stock": 21,
  },
  {
    "name": "The Outer Worlds",
    "image": "https://res.cloudinary.com/bits8/image/upload/v1694110448/mdresf872bhozjxokcu3.jpg",
    "description": "A spacefaring RPG with a darkly comedic take on a dystopian future.",
    "releaseDate": "October 25, 2019",
    "supportedPlatforms": ["PC", "PlayStation 4", "Xbox One", "Nintendo Switch"],
    "genre": ["RPG"],
    "price": 21.50,
    "review": "Metacritic Score - 82/100",
    "stock": 17,
  },
  {
    "name": "Outer Wilds",
    "image": "https://res.cloudinary.com/bits8/image/upload/v1694449065/bywptvdloerp7du8m89p.jpg",
    "description": "An open-world mystery about a solar system trapped in an endless time loop.",
    "releaseDate": "June 18, 2020",
    "supportedPlatforms": ["PC", "PlayStation 4", "Xbox One", "Nintendo Switch"],
    "genre": ["Adventure"],
    "price": 19.90,
    "review": "Metacritic Score - 85/100",
    "stock": 20,
   },
    {
      "name": "Genshin Impact",
      "image": "https://res.cloudinary.com/bits8/image/upload/v1695320493/mcu3oog85w0ehkggqqam.jpg",
      "description": "An open-world action RPG with elemental magic and a diverse cast of characters.",
      "releaseDate": "September 28, 2020",
      "supportedPlatforms": ["PC", "PlayStation 4", "PlayStation 5", "iOS", "Android"],
      "genre":["Action"],
      "price": 9.90,
      "review": "Metacritic Score - 82/100", 
      "stock" : 33,
    },
    {
      "name": "Sackboy: A Big Adventure",
      "image": "https://res.cloudinary.com/bits8/image/upload/v1695322122/t2unepfqwqqthbzdiz1c.jpg",
      "description": "Join Sackboy on a platforming adventure in a whimsical world full of challenges.",
      "releaseDate": "November 12, 2020",
      "supportedPlatforms": ["PlayStation 4", "PlayStation 5"],
      "genre": ["Platformer"],
      "price": 15.90,
      "review": "Metacritic Score - 78/100",
      "stock" : 30,
    },
    {
      "name": "Star Wars Jedi: Fallen Order",
      "image": "https://res.cloudinary.com/bits8/image/upload/v1695322209/l60olifubcj2juoxrrv5.jpg",
      "description": "Become a Jedi in this action-adventure game set in the Star Wars universe.",
      "releaseDate": "November 15, 2019",
      "supportedPlatforms": ["PC", "PlayStation 4", "Xbox One", "PlayStation 5", "Xbox Series X/S"],
      "genre": ["Action", "Adventure"],
      "price": 25.90,
      "review": "Metacritic Score - 82/100",
      "stock" : 45,
    },
    {
      "name": "Halo: Infinite",
      "image": "https://res.cloudinary.com/bits8/image/upload/v1695322434/udsqvfexn5dys5jgxyy9.jpg",
      "description": "Master Chief returns in this first-person shooter as he battles the Banished on a Halo ring.",
      "releaseDate": "December 8, 2021",
      "supportedPlatforms": ["PC", "Xbox One", "Xbox Series X/S"],
      "genre": ["First-Person Shooter"],
      "price": 29.90,
      "review": "Metacritic Score - 76/100",
      "stock" : 55,
    },
    {
      "name": "Horizon Forbidden West",
      "image": "https://res.cloudinary.com/bits8/image/upload/v1695322532/hrzfrnnpqxdbvlxj3vbx.jpg",
      "description": "Continue Aloy's journey in this open-world action RPG set in a post-apocalyptic future.",
      "releaseDate": "February 18, 2022",
      "supportedPlatforms": ["PlayStation 4", "PlayStation 5"],
      "genre": ["Action", "RPG"],
      "price": 39.90,
      "review": "Metacritic Score - 88/100",
      "stock" : 48,
    },
    {
      "name": "Elden Ring",
      "image": "https://res.cloudinary.com/bits8/image/upload/v1695322615/g1xzku4rh299vl3snntu.jpg",
      "description": "A dark fantasy action RPG developed in collaboration with George R.R. Martin.",
      "releaseDate": "February 25, 2022",
      "supportedPlatforms": ["PC", "PlayStation 4", "PlayStation 5", "Xbox One", "Xbox Series X/S"],
      "genre": ["Action", "RPG"],
      "price": 29.90,
      "review": "Metacritic Score - 89/100",
      "stock" : 20,
    },
    {
      "name": "Spider-Man: Miles Morales",
      "image": "https://res.cloudinary.com/bits8/image/upload/v1695322891/vukngpqzea3fggks4mvg.jpg",
      "description": "Play as Miles Morales in this superhero action-adventure game set in New York City.",
      "releaseDate": "November 12, 2020",
      "supportedPlatforms": ["PlayStation 4", "PlayStation 5"],
      "genre": ["Action", "Adventure"],
      "price": 39.90,
      "review": "Metacritic Score - 85/100",
      "stock" : 40,
    },
    {
      "name": "Resident Evil 7: Biohazard",
      "image": "https://res.cloudinary.com/bits8/image/upload/v1695322976/mg5kb35otbjgqv5nmqlp.jpg",
      "description": "Survive a horrifying ordeal in this first-person survival horror game.",
      "releaseDate": "January 24, 2017",
      "supportedPlatforms": ["PC", "PlayStation 4", "Xbox One"],
      "genre": [ "Survival Horror"],
      "price": 24.90,
      "review": "Metacritic Score - 86/100",
      "stock" : 10,
    },
    {
      "name": "The Sims 4",
      "image": "https://res.cloudinary.com/bits8/image/upload/v1695323050/ylaxojduwcrist6cramr.jpg",
      "description": "Create and control simulated people in this popular life simulation game.",
      "releaseDate": "September 2, 2014",
      "supportedPlatforms": ["PC", "PlayStation 4", "Xbox One"],
      "genre": ["Life Simulation"],
      "price": 19.90,
      "review": "Metacritic Score - 70/100",
      "stock" : 39,
    },
    {
      "name": "Final Fantasy XVI",
      "image": "https://res.cloudinary.com/bits8/image/upload/v1695323344/xuofvoxfkthf7nph0tbx.jpg",
      "description": "Enter a new world of fantasy in this upcoming action RPG.",
      "releaseDate": "June 22, 2023",
      "supportedPlatforms": ["TBD"],
      "genre": ["Action", "RPG"],
      "price": 49.90,
      "review": "Metacritic Score - 80/100",
      "stock" : 22, 
    },
    {
      "name": "Ratchet & Clank: Rift Apart",
      "image": "https://res.cloudinary.com/bits8/image/upload/v1695323448/qji2h8nmrmxt3p1qyqys.jpg",
      "description": "Join Ratchet and Clank in an interdimensional adventure in this action-adventure game.",
      "releaseDate": "June 11, 2021",
      "supportedPlatforms": ["PlayStation 5"],
      "genre": ["Action", "Adventure"],
      "price": 35.90,
      "review": "Metacritic Score - 88/100",
      "stock" : 30,
    },
    {
      "name": "FIFA 22",
      "image": "https://res.cloudinary.com/bits8/image/upload/v1695323602/hubsvz6vpxt41m4esq9v.jpg",
      "description": "Experience the latest installment of the popular soccer simulation game.",
      "releaseDate": "October 1, 2021",
      "supportedPlatforms": ["PC", "PlayStation 4", "PlayStation 5", "Xbox One", "Xbox Series X/S"],
      "genre": ["Sports"],
      "price": 45.90,
      "review": "Metacritic Score - 75/100",
      "stock" : 38,
    },
    {
      "name": "Biomutant",
      "image": "https://res.cloudinary.com/bits8/image/upload/v1695323746/xlbtj8q5flfk3s6qsrzl.jpg",
      "description": "Embark on an open-world adventure as a mutated creature in this action RPG.",
      "releaseDate": "May 25, 2021",
      "supportedPlatforms": ["PC", "PlayStation 4", "Xbox One"],
      "genre": ["Action", "RPG"],
      "price": 34.90,
      "review": "Metacritic Score - 65/100",
      "stock" : 45,
    },
    {
      "name": "Watch Dogs: Legion",
      "image": "https://res.cloudinary.com/bits8/image/upload/v1695324092/mttp6ir50x1if4oql7hl.jpg",
      "description": "Hack your way through London in this open-world action-adventure game.",
      "releaseDate": "October 29, 2020",
      "supportedPlatforms": ["PC", "PlayStation 4", "PlayStation 5", "Xbox One", "Xbox Series X/S"],
      "genre": ["Action", "Adventure"],
      "price": 34.90,
      "review": "Metacritic Score - 70/100",
      "stock" : 51,
    },
    {
      "name": "Metroid Dread",
      "image": "https://d1w82usnq70pt2.cloudfront.net/wp-content/uploads/2021/10/MetroidDreadBanner-1.jpg",
      "description": "Join Samus Aran on a thrilling 2D action-adventure in this Metroid series game.",
      "releaseDate": "October 8, 2021",
      "supportedPlatforms": ["Nintendo Switch"],
      "genre": ["Action", "Adventure"],
      "price": 15.90,
      "review": "Metacritic Score - 88/100",
      "stock" : 33,
    },
    {
      "name": "Returnal",
      "image": "https://res.cloudinary.com/bits8/image/upload/v1695324260/ekkfpcbttygi2hxwxisl.jpg",
      "description": "Navigate a mysterious alien world in this roguelike third-person shooter.",
      "releaseDate": "April 30, 2021",
      "supportedPlatforms": ["PlayStation 5"],
      "genre": ["Roguelike"],
      "price": 29.90,
      "review": "Metacritic Score - 86/100",
      "stock" : 45,
    },
    {
      "name": "Hitman 3",
      "image": "https://res.cloudinary.com/bits8/image/upload/v1695324394/lujad9mqhzpfbhouopzj.jpg",
      "description": "Become Agent 47 and eliminate targets in this stealthy assassination game.",
      "releaseDate": "January 20, 2021",
      "supportedPlatforms": ["PC", "PlayStation 4", "PlayStation 5", "Xbox One", "Xbox Series X/S"],
      "genre": ["Stealth"],
      "price": 25.90,
      "review": "Metacritic Score - 83/100",
      "stock" : 22,
    },
    {
      "name": "Hogwarts Legacy",
      "image": "https://res.cloudinary.com/bits8/image/upload/v1695324639/scnjwh7jwp1hl1l1bwy3.jpg",
      "description": "Explore the magical world of Harry Potter in this action RPG set at Hogwarts.",
      "releaseDate": "February 10, 2023",
      "supportedPlatforms": ["PC", "PlayStation 4", "PlayStation 5", "Xbox One", "Xbox Series X/S"],
      "genre": ["Action", "RPG"],
      "price": 59.90,
      "review": "Metacritic Score - 90/100",
      "stock" : 28,
    },
    {
      "name": "Splatoon 3",
      "image": "https://res.cloudinary.com/bits8/image/upload/v1695324902/r4i3acmjuh1bqw1sqnpu.jpg",
      "description": "Return to the colorful ink-splatting world in the third installment of the series.",
      "releaseDate": "September 2, 2014",
      "supportedPlatforms": ["Nintendo Switch"],
      "genre": ["First-Person Shooter"],
      "price": 34.90,
      "review": "Metacritic Score - 70/100",
      "stock" : 25, 
    },
    
  ];

async function createGame(req, res) {
  try {
    for (const gameData of gamesArray) {
      const { name, image, description, releaseDate, supportedPlatforms, genre, price, review, stock } = gameData;
      const newGame = await Game.create({
        name,
        image,
        description,
        releaseDate,
        price,
        review,
        stock,
      });

      for (const genreName of genre) {
        const genreInstance = await Genre.findOne({ where: { name: genreName } });
        if (genreInstance) {
          await newGame.addGenre(genreInstance);
        }
      }

      for (const platformName of supportedPlatforms) {
        const platformInstance = await SupportedPlatform.findOne({ where: { name: platformName } });
        if (platformInstance) {
          await newGame.addSupportedPlatform  (platformInstance);
        }
      }
    }
    res.status(201).json({ message: 'Games created successfully' });
  } catch (error) {
    console.error('Error creating games', error);
    res.status(500).json({ error: 'Error creating games' });
  }
}

const gameGenres = [
  "Action",
  "Adventure",
  "Role-Playing",
  "First-Person Shooter",
  "Third-Person Shooter",
  "Platformer",
  "Racing",
  "Sports",
  "Simulation",
  "Strategy",
  "Puzzle",
  "Fighting",
  "Survival Horror",
  "Open World",
  "Sandbox",
  "Stealth",
  "Tactical",
  "Educational",
  "Music/Rhythm",
  "Party/Mini-Games",
  "Card and Board Games",
  "Visual Novel",
  "Point-and-Click",
  "Horror",
  "Science Fiction (Sci-Fi)",
  "Fantasy",
  "Historical",
  "Western",
  "Anime",
  "Cartoon/Cel-Shaded",
  "Mystery",
  "Interactive Fiction",
  "Roguelike/Roguelite",
  "Metroidvania",
  "Tower Defense",
  "MOBA (Multiplayer Online Battle Arena)",
  "Battle Royale",
  "MMO (Massively Multiplayer Online)",
  "Farming/Simulation",
  "City Building/Management",
  "Life Simulation",
  "Action RPG",
  "Roguelike",
  "Action-Adventure",
  "JRPG",
  "RPG",
  "Run and Gun",
];

async function loadGenres(req, res) {
  try {
    const genres = await gameGenres.forEach((genre) => {
      Genre.findOrCreate({
        where: { name: genre }
      })
    });
    res.status(201).json({ message: 'Genres loaded with success', genres });
  } catch (error) {
    console.error('Error loading genres', error);
    res.status(500).json({ error: 'Error loading genres' });
  }
};

const listPlatform = [
  "Nintendo Switch",
  "Wii U",
  "PC",
  "PlayStation 4",
  "Xbox One",
  "PlayStation 3",
  "Xbox 360",
  "PlayStation 5",
  "Xbox Series X/S",
  "Various consoles",
  "Mobile devices",
  "iOS",
  "Android",
  "TBD",
];

async function loadSupportedPlatform(req, res) {
  try {
    const platform = await listPlatform.forEach((e) => {
      SupportedPlatform.findOrCreate({
        where: { name: e }
      })
    });
    res.status(201).json({ message: 'Supported Platform loaded with success', platform });
  } catch (error) {
    console.error('Error loading Supported Platform', error);
    res.status(500).json({ error: 'Error loading Supported Platform' });
  }
};

module.exports = {
  createGame,
  loadGenres,
  loadSupportedPlatform,
};

